### ISSUE TITLE
Fails with import error 

### ISSUE THREAD

**Issue by Dunedan** [Lucas-C/pre-commit-hooks-bandit#1]
Same issue as https://github.com/Lucas-C/pre-commit-hooks-safety/issues/2

Renaming `bandit.py` gets it working as well.

I'm not sure why it works right now with TravisCI. The only notable difference I see is that I've tried running it with Python 2.7, although I was able to reproduce the issue with Python 3.5 as well.

**Comment by Lucas-C** [comment]
Should be good now.
Can you check please ?

**Comment by Dunedan** [comment]
Works as it should now. Thanks very much. :smile:
